# Generated by Django 4.2 on 2025-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quiz_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
