# Generated by Django 4.2 on 2025-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_chapter_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='manager',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
