# Generated by Django 4.2 on 2025-02-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
