# Generated by Django 4.2 on 2025-02-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_attachment_attached_file_attachment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.course'),
        ),
    ]
