# Generated by Django 4.2 on 2025-02-15 18:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_attachment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('purchase_id', models.CharField(max_length=255, null=True, unique=True)),
                ('access_type', models.CharField(default='Lifetime', max_length=30)),
                ('progress', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_url', models.CharField(blank=True, max_length=255, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
