# Generated by Django 4.2 on 2025-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
