# Generated by Django 4.2 on 2025-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_usercourse_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='access_type',
            field=models.CharField(default='Lifetime', max_length=30),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='certificate_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='purchase_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
