# Generated by Django 4.2 on 2025-02-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_usercourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='progress',
            field=models.CharField(choices=[('progress', 'progress'), ('completed', 'completed')], default='progress', max_length=15, null=True),
        ),
    ]
