# Generated by Django 4.2 on 2025-02-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_usercourse_is_complete_alter_usercourse_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
