# Generated by Django 4.2 on 2025-02-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_usercourse_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='progress',
            field=models.IntegerField(null=True),
        ),
    ]
