# Generated by Django 4.2 on 2025-02-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_usercourse_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='progress',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
