# Generated by Django 4.2 on 2025-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_purchase_amount_alter_purchase_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
