# Generated by Django 4.2 on 2025-02-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_purchase_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='course_id',
            new_name='course',
        ),
    ]
