# Generated by Django 4.2 on 2025-02-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_course_id_purchase_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='course',
        ),
    ]
