# Generated by Django 4.2 on 2025-02-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_purchase_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='course_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
